# Generated by Django 3.2.9 on 2021-11-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
