# Generated by Django 3.2.9 on 2021-11-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_test_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='text',
            field=models.FloatField(),
        ),
    ]
