# Generated by Django 3.2.9 on 2021-11-12 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_test_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content_text', models.TextField()),
                ('links', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('user_name', models.CharField(max_length=150)),
                ('artist', models.BooleanField()),
                ('biography', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TextMeasure',
            fields=[
                ('text_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('good_text', models.TextField()),
                ('neutral_text', models.TextField()),
                ('bad_text', models.TextField()),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_measure', to='mainpage.rating')),
            ],
        ),
        migrations.CreateModel(
            name='ScaleMeasure',
            fields=[
                ('scale_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lower_bound', models.FloatField()),
                ('upper_bound', models.FloatField()),
                ('unit', models.FloatField()),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scale_measure', to='mainpage.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('opinion', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mainpage.user')),
                ('publications', models.ManyToManyField(related_name='reviews', to='mainpage.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_ratings', to='mainpage.user'),
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', to='mainpage.review'),
        ),
        migrations.AddField(
            model_name='rating',
            name='users',
            field=models.ManyToManyField(related_name='ratings_used', to='mainpage.User'),
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='mainpage.user'),
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('image_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='mainpage.user')),
            ],
        ),
        migrations.CreateModel(
            name='PercentageMeasure',
            fields=[
                ('percentage_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('upper_bound', models.FloatField()),
                ('unit', models.FloatField()),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='percentage_measure', to='mainpage.rating')),
            ],
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('image_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainpage.content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='publication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='mainpage.publication'),
        ),
    ]
